# Generated by Django 3.0.3 on 2020-03-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200306_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
